import fs from 'fs';

const sqlFunc = `
CREATE OR REPLACE FUNCTION public.get_active_tenant_id()
RETURNS uuid
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT tenant_id FROM public.profiles WHERE id = auth.uid() LIMIT 1;
$$;
`;

const file = 'supabase/migrations/20260520000000_crear_viajeros_maestro.sql';
let content = fs.readFileSync(file, 'utf8');

// Strip BOM if present
if (content.charCodeAt(0) === 0xFEFF || content.charCodeAt(0) === 0xFFFE) {
  content = content.slice(1);
}

// Remove the null bytes generated by PowerShell UTF-16
content = content.replace(/\0/g, '');

fs.writeFileSync(file, sqlFunc + '\n' + content, 'utf8');
console.log('Archivo SQL preparado y limpio en UTF-8 puro.');
